### ISSUE TITLE
Wire-up uninstall

### ISSUE THREAD

**Issue by rpappalax** [mozilla/ff-tool#32]
logic should already be in place.  We just need to add an arg for it to main.py.

something like:

-u <channel name>

**Comment by pdehaan** [comment]
The one gotcha I see on Windows is that if you have an existing "Beta" or "Nightly" installed and configured, there is a 90% chance we'll just kill that install since Windows dumps everything in C:/Program Files/ so we can't manage our own install (unless we can sort #33).

OSX and Linux are easier since we can put the runtimes anywhere we want and just `rm -rf` them at will without worrying about breaking a user's existing install.

**Comment by rpappalax** [comment]
hmm, that's true. This is a thorny problem.
Do you happen to know anyone who works as a windows dev on FF?  We could certainly keep googling this, but it might help if we had some inside knowledge to turn to.

**Comment by pdehaan** [comment]
I know nobody. Can't even say that I know who the FF Desktop QA team is anymore. We could try pinging RyanVM or sphilp or mwobensmith maybe.

**Comment by rpappalax** [comment]
Ah yes.  good call

**Comment by rpappalax** [comment]
This module was written in the good ole days and will need some updating.  There is a reference to a "cache.ini" file which pre-dates us even using the _temp (.cache) dir, so we'll need to clean this up:
https://github.com/rpappalax/ff-tool/blob/dev/fftool/firefox_uninstall.py#L29-L32
